apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: inventory-serviceaccount
      containers:
        - name: inventory
          image: microshop.azurecr.io/inventory.service:1.0.4
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: microshop
            - name: ServiceSettings__Authority
              value: https://microshop.westus2.cloudapp.azure.com/identity-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5004
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5004
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5004
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - port: 80
      targetPort: 5004

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-serviceaccount
  annotations:
    azure.workload.identity/client-id: 1d6c7410-2913-40c2-82e1-0401c2cad99e
  labels:
    azure.workload.identity/use: "true"
